import type { ClipboardItem, ClipboardSnapshot, LyricLine, PrivacySnapshot, SettingsPage, TrackState } from "../state";

export interface ViewSyncContext {
  [key: string]: any;
  app: HTMLElement;
  track: TrackState;
  progressSeconds: number;
  lyrics: LyricLine[];
  systemMediaActive: boolean;
  lastLyricsDataKey: string;
  lyricsCenterFrame: number;
  mode: IslandMode;
  glassStyle: GlassStyle;
  glassIntensity: GlassIntensity;
  playing: boolean;
  favorited: boolean;
  draggingProgress: boolean;
  mediaEntering: boolean;
  mediaExiting: boolean;
  capsuleAppearing: boolean;
  capsuleDisappearing: boolean;
  privacyState: PrivacySnapshot;
  priorityTransition: string;
  priorityTransitionStage: string;
  clipboardPromptVisible: boolean;
  settingsPage: SettingsPage;
  layout: IslandLayout;
  systemMonitorEnabled: boolean;
  systemSnapshot: SystemSnapshot;
  privacyExpanded: boolean;
  clipboardSnapshot: ClipboardSnapshot;
  clipboardAccepting: boolean;
  clipboardAcceptPreview: string;
  clipboardListRenderKey: string;
  clipboardDeleteDialogItemId: string;
  expandedLayerPrewarmed: boolean;
  getDisplayedLyrics(): LyricLine[];
  getActiveLyricIndex(): number;
  getAvailableCardModes(): IslandMode[];
  hasClipboardItems(): boolean;
  isIdleSystemActive(): boolean;
  formatTime(seconds: number): string;
  progressPercent(): string;
  getClipboardPreviewText(): string;
  getPendingClipboardItem(): ClipboardItem | undefined;
  getAcceptedClipboardItem(): ClipboardItem | undefined;
  formatClipboardTime(timestamp: number): string;
  getClipboardItemById(itemId: string): ClipboardItem | undefined;
  isCardMode(mode?: IslandMode): boolean;
  getPrivacyLabel(kind: PrivacySnapshot["kind"]): string;
  getPrivacyDetailText(kind: PrivacySnapshot["kind"]): string;
}
