import {
  Activity,
  ChevronLeft,
  ChevronRight,
  Clipboard,
  Cpu,
  Gauge,
  HardDrive,
  Heart,
  MemoryStick,
  Music2,
  Pause,
  Play,
  SkipBack,
  SkipForward
} from "lucide";

export const lucideIcons = {
  Activity,
  ChevronLeft,
  ChevronRight,
  Clipboard,
  Cpu,
  Gauge,
  HardDrive,
  Heart,
  MemoryStick,
  Music2,
  Pause,
  Play,
  SkipBack,
  SkipForward,
  activity: Activity,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  clipboard: Clipboard,
  cpu: Cpu,
  gauge: Gauge,
  "hard-drive": HardDrive,
  heart: Heart,
  "memory-stick": MemoryStick,
  "music-2": Music2,
  pause: Pause,
  play: Play,
  "skip-back": SkipBack,
  "skip-forward": SkipForward
};
